### PR TITLE
Add annotated progress graph

### PR DESCRIPTION
**Pull request by delijati**
Add annotated progress graph. The provided `access.log` had only two days ;)

### CODE REVIEW

**Review by mariogrip — CHANGES_REQUESTED** [review]
Hi! it looks really good! but could you remove the "package-lock.json" since that get's auto-created by npm install

**Comment by delijati** [comment]
Done

**Comment by mariogrip** [comment]
Awesome thanks! :)

**Comment by delijati** [comment]
is it running for you i get this error `WebSocket connection to 'wss://stats.ubports.com/socket.io/?EIO=3&transport=websocket&sid=g0zXMfnog6bEd4RcAAAS' failed: Error during WebSocket handshake: Unexpected response code: 400`

**Pull request merged**
